### ISSUE TITLE
Attributes are sorted?

### ISSUE THREAD

**Issue by thheller** [weavejester/hiccup#141]
I was debugging some HTML generation and ended up with an uncompiled hiccup form which went through the `hiccup.compiler/render-html` protocol. I noticed that attributes are sorted?

https://github.com/weavejester/hiccup/blob/master/src/hiccup/compiler.clj#L57

Why are they sorted? The cost isn't that significant for fully compiled forms but otherwise the `apply` and `sort` seem like a performance waste?

**Comment by weavejester** [comment]
If they're not sorted then you get an unpredictable output. The same data structure can result in different output strings. This can cause a problem if you're trying to cache the output, and of course it means that the function is no longer pure.

**Comment by thheller** [comment]
Well the order of attributes in html is irrelevant so it should not matter? Not sure I buy the "pure" argument either as the any clojure datastructure will always `seq` in the same manner thus preserving order?

**Comment by weavejester** [comment]
It matters if the cache is not aware of the original data structure, and we're just performing a string or byte comparison to check equality. It doesn't matter if two strings of HTML are equivalent if we can't easily tell that they're equivalent.

Ensuring that the equivalent input produces equivalent output is a useful enough property that it's worth the minor cost of having an additional `sort`. In many cases attributes are literal, so there's no runtime cost, and even in extreme cases the performance cost is relatively minor. For example, dynamically rendering 1000 elements with attributes, removing the `sort` results in a 5% reduction in execution time.

**Comment by thheller** [comment]
Thanks for the reply. I guess it is really not that important since most of it will be precompiled anyways.

**Comment by diegobfernandez** [comment]
Sorry for resurrecting the issue, but I just faced an issue with [datastar](https://github.com/starfederation/datastar) which expects signals declarations in attributes to be declared in order.
Not saying this is something that should be fixed, but a clear pointer in the docs would be nice :)

**Comment by weavejester** [comment]
> Sorry for resurrecting the issue, but I just faced an issue with [datastar](https://github.com/starfederation/datastar) which expects signals declarations in attributes to be declared in order.

Can you explain what you mean by this?

**Comment by diegobfernandez** [comment]
### Note

I had this reply ready for a while but since I wrote this datastar released a new version which I can't use for open-source projects, hence I've moved to hotwired turbo instead.

The new version also don't mention that "attributes are evaluated in the order they appear in the DOM". So this might not be an issue anymore, but I did not test it.

There is also a new website, so in order for the links to make sense I've used Web Archive ones.

____

### Original text

I was following [this guide](https://web.archive.org/web/20250411210908/https://data-star.dev/guide/getting_started) in the official datastar docs and I converted this example from HTML to hiccup:

```html
<div
  data-signals="{response: '', answer: 'bread'}"
  data-computed-correct="$response.toLowerCase() == $answer"
>
    ... omitted ...
</div>
```

```clojure
[:div {:data-signals {:response "" :answer "bread"}
       :data-computed-correct "$response.toLowerCase() == $answer"}]
```

When migrating to hiccup I got a runtime error in datastar's client library, saying `$response` is not defined. Once I inspected the page source I saw that the output HTML had attributes sorted.

```html
<div
  data-computed-correct="$response.toLowerCase() == $answer"
  data-signals="{response: '', answer: 'bread'}"
>
    ... omitted ...
</div>
```

Datastar docs state ([link](https://web.archive.org/web/20250411210908/https://data-star.dev/guide/getting_started)):

> Note that data-* attributes are evaluated in the order they appear in the DOM, so the data-text attribute must come after the data-bind attribute. See the [attribute plugins reference](https://web.archive.org/web/20250411210908/https://data-star.dev/reference/attribute_plugins) for more information.

**Comment by weavejester** [comment]
Unfortunately not something we can easily fix; Clojure maps are unordered. Using an [ordered map](https://github.com/clj-commons/ordered) *might* work.
