### ISSUE TITLE
Hiccup manipulates nested macro calls

### ISSUE THREAD

**Issue by habruening** [weavejester/hiccup#216]
This looks incorrect to me. Hiccup goes into the the argument and manipulates the type. `jqu (as)` produces a clojure.lang.PersistentList. But Hiccup sometimes converts it to a clojure.lang.Cons.

````
(defmacro jqu [code] 
  (str (type code)))

(jqu (as))

(str (h/html [:body      (jqu (as))]))
  => "<body>class clojure.lang.PersistentList</body>"

(str (h/html [:body [:p] (jqu (as))]))
  => "<body><p></p>class clojure.lang.Cons</body>"
````

I have a workaround for this.

````
(let [hiccup-vector [:body [:p] (jqu (as))]]
  (str (h/html hiccup-vector)))
````

But is that behaviour expected? I think, Hiccup should not try to go into macro calls and change something there.

**Comment by weavejester** [comment]
In Clojure, PersistentList and Cons are both classes that can represent a list. Which one is used is an internal detail. There may be something in the Hiccup compiler that triggers Clojure to convert one to the other, but this doesn't affect how Hiccup operates.

**Comment by habruening** [comment]
But it affects how the macro jqu operates in this case. Isn't it unexpected that a macro operates differently inside Hiccup and outside Hiccup. I can imagine use cases of macros that explicitly test for PersistentList. I think, for macros this is quite common. In many cases this is the only reason why you want to use a macro. Retard the evaluation for PersistentList lists.
But after looking into it a bit I think, we shouldn't fix this in Hiccup. It will be too complicated, I think. There is a lot of  macro magic involved in Hiccup. The workaround works perfectly. Maybe Hiccup could offer that workaround as a function. That would also be helpful for people who struggle with macro expansions that are too big.

**Comment by weavejester** [comment]
This is more a "Clojure" problem than a "Hiccup" one. Clojure assumes that PersistentList and Cons are interchangeable. If you have code that works with a PersistentList but not a Cons, that code is wrong, because a list may be either type. You should be using the IPersistentList interface instead.

There are several cases where Clojure uses several classes for the same data type. This implementation detail of Clojure. Hiccup is returning a list, which is correct; it doesn't matter if this list is a PersistentList or a Cons, as both classes represent a list.

**Comment by habruening** [comment]
Indeed, you are right. I did not expect that.
This indeed works:
````
(defmacro execute []
  (cons '+ '(2 3)))

(execute)
````
I thought, the evaluator would not evaluate it, because it is not a PersitentList. But it indeed returns 5.
So I think, I have to change my macros. Then Hiccup will work again. Thanks.
